# Generated by Django 3.1.5 on 2021-01-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='external_app',
            new_name='user',
        ),
    ]
