# Generated by Django 3.1.5 on 2021-01-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210116_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='Example', max_length=200),
            preserve_default=False,
        ),
    ]
