# Generated by Django 3.1.5 on 2021-01-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='activation_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
